# Generated by Django 3.0.6 on 2020-05-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200509_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_best',
            field=models.BooleanField(default=False),
        ),
    ]
