# Generated by Django 3.0.6 on 2020-06-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200523_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='twitter_screenname',
            field=models.CharField(default='screeeeen', max_length=100, null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
