# Generated by Django 3.0.6 on 2020-06-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20200602_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='twitter_screenname',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
