# Generated by Django 3.0.6 on 2020-06-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20200602_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_changed_username',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
