# Generated by Django 3.0.6 on 2020-06-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20200604_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='twitter_pic_url',
            field=models.CharField(default='https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png', max_length=100),
        ),
    ]
